version: '3'
services:
  discovery-server:
    container_name: warmsnow-discovery
    build:
      context: ../discovery-server
      dockerfile: Dockerfile
    image: mrlanu/warmsnow-discovery-server:0.0.1-SNAPSHOT
#    entrypoint: /opt/bin/discovery-server-entrypoint.sh
#    depends_on:
#      - config-server
    environment:
#      - SPRING_CLOUD_CONFIG_URI=http://config-server:10000
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8001:8001
    networks:
      - warmsnow-network
  config-server:
    container_name: warmsnow-config
    build:
      context: ../config-server
      dockerfile: Dockerfile
    image: mrlanu/warmsnow-config-server:0.0.1-SNAPSHOT
#    depends_on:
#      - rabbit-mq-management
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH-LOCATIONS=file:///config-warmsnow
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-server:8001/eureka/
#      - SPRING_RABBITMQ_HOST=rabbit-mq-management
    volumes:
      - ../config-server/src/main/resources/shared:/config-warmsnow
    expose:
      - 10000
    ports:
      - 10000:10000
    networks:
      - warmsnow-network
  gateway-server:
    container_name: warmsnow-gateway
    build:
      context: ../gateway-server
      dockerfile: Dockerfile
    image: mrlanu/warmsnow-gateway-server:0.0.1-SNAPSHOT
#    entrypoint: /opt/bin/gateway-server-entrypoint.sh
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-server:8001/eureka/
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - warmsnow-network
networks:
  warmsnow-network:
    driver: bridge
